### ISSUE TITLE
Add Capacitor 3 support

### ISSUE THREAD

**Issue by dennisameling** [hinddeep/ionicCapacitorDarkMode#10]
Could you please add Capacitor 3 support to this plugin? They've recently launched a Release Candidate, so it should go live within a few weeks from now. Please let the community know in this issue if you need community help with this!

**Comment by micahlt** [comment]
Full support for this - I'm having major issues with this plugin and Capacitor 3.

**Comment by micahlt** [comment]
@dennisameling @hinddeep I just made a pull request (#12) that fixes compatibility with Capacitor 3.  Until this gets merged anyone is welcome to use it from my fork: `npm i git://github.com/micahlt/ionicCapacitorDarkMode --save`

**Comment by riderx** [comment]
@micahlt can you publish your module i will replace it from : https://github.com/riderx/awesome-capacitor

**Comment by micahlt** [comment]
@riderx here you are: https://www.npmjs.com/package/@micahlt/capacitor-dark-mode

I am also working on a few documentation improvements, so keep an eye out for an update.

**Comment by riderx** [comment]
Thanks i added your version.
A great doc can really make your version Awesome :)
You can start by having code block for code in readme, it will make it way better

**Comment by hinddeep** [comment]
I've merged the pull request that supports Capacitor 3.
